//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;
namespace StudentManagement.Module.BusinessObjects.StudentManagement
{
    [DefaultClassOptions]
    public partial class Diemso : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Sinhvien fMaSinhvien;
        [Association(@"DiemsoReferencesSinhvien")]
        [DevExpress.Xpo.DisplayName(@"Mã sinh viên")]
        public Sinhvien MaSinhvien
        {
            get { return fMaSinhvien; }
            set { SetPropertyValue<Sinhvien>(nameof(MaSinhvien), ref fMaSinhvien, value); }
        }
        Diemchitiet fDiemchitietID;
        [Association(@"DiemsoReferencesDiemchitiet")]
        public Diemchitiet DiemchitietID
        {
            get { return fDiemchitietID; }
            set { SetPropertyValue<Diemchitiet>(nameof(DiemchitietID), ref fDiemchitietID, value); }
        }
        double fKyHoc;
        [DevExpress.Xpo.DisplayName(@"Kỳ học")]
        public double KyHoc
        {
            get { return fKyHoc; }
            set { SetPropertyValue<double>(nameof(KyHoc), ref fKyHoc, value); }
        }
        string fNamHoc;
        [DevExpress.Xpo.DisplayName(@"Năm học")]
        public string NamHoc
        {
            get { return fNamHoc; }
            set { SetPropertyValue<string>(nameof(NamHoc), ref fNamHoc, value); }
        }
        string fXepLoai;
        [PersistentAlias("Iif([DiemchitietID.DiemTongKet] >= 8.5, 'Giỏi', Iif([DiemchitietID.DiemTongKet] >= 7.0, 'Khá', Iif([DiemchitietID.DiemTongKet] >= 5.5, 'Trung bình', Iif([DiemchitietID.DiemTongKet] >= 4.0, 'Yếu', 'Kém'))))")]
        public string XepLoai
        {
            get { return (string)(EvaluateAlias(nameof(XepLoai))); }
        }
    }

}
