//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;
namespace StudentManagement.Module.BusinessObjects.StudentManagement
{
    [DefaultClassOptions]
    public partial class Lichhoc : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Sinhvien fMaSinhVien;
        [Association(@"LichhocReferencesSinhvien")]
        [DevExpress.Xpo.DisplayName(@"Mã sinh viên")]
        public Sinhvien MaSinhVien
        {
            get { return fMaSinhVien; }
            set { SetPropertyValue<Sinhvien>(nameof(MaSinhVien), ref fMaSinhVien, value); }
        }
        Monhoc fMonhocID;
        [Association(@"LichhocReferencesMonhoc")]
        public Monhoc MonhocID
        {
            get { return fMonhocID; }
            set { SetPropertyValue<Monhoc>(nameof(MonhocID), ref fMonhocID, value); }
        }
        DateTime fNgayHoc;
        [DevExpress.Xpo.DisplayName(@"Ngày học")]
        public DateTime NgayHoc
        {
            get { return fNgayHoc; }
            set { SetPropertyValue<DateTime>(nameof(NgayHoc), ref fNgayHoc, value); }
        }
        TimeSpan fGioHoc;
        [DevExpress.Xpo.DisplayName(@"Giờ học")]
        public TimeSpan GioHoc
        {
            get { return fGioHoc; }
            set { SetPropertyValue<TimeSpan>(nameof(GioHoc), ref fGioHoc, value); }
        }
        string fPhongHoc;
        [DevExpress.Xpo.DisplayName(@"Phòng học")]
        public string PhongHoc
        {
            get { return fPhongHoc; }
            set { SetPropertyValue<string>(nameof(PhongHoc), ref fPhongHoc, value); }
        }
        bool fNotificationSent;
        [DevExpress.Xpo.DisplayName(@"Đã Gửi Thông Báo")]
        public bool NotificationSent
        {
            get { return fNotificationSent; }
            set { SetPropertyValue<bool>(nameof(NotificationSent), ref fNotificationSent, value); }
        }
        [Association(@"DiemdanhReferencesLichhoc"), Aggregated]
        public XPCollection<Diemdanh> Diemdanhs { get { return GetCollection<Diemdanh>(nameof(Diemdanhs)); } }
    }

}
