//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;
namespace StudentManagement.Module.BusinessObjects.StudentManagement
{
    [DefaultClassOptions]
    [DefaultProperty("TenMon")]
    public partial class Monhoc : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fTenMon;
        [DevExpress.Xpo.DisplayName(@"Tên môn")]
        public string TenMon
        {
            get { return fTenMon; }
            set { SetPropertyValue<string>(nameof(TenMon), ref fTenMon, value); }
        }
        double fSoTC;
        [DevExpress.Xpo.DisplayName(@"Số TC")]
        public double SoTC
        {
            get { return fSoTC; }
            set { SetPropertyValue<double>(nameof(SoTC), ref fSoTC, value); }
        }
        string fMoTa;
        [DevExpress.Xpo.DisplayName(@"Mô tả")]
        public string MoTa
        {
            get { return fMoTa; }
            set { SetPropertyValue<string>(nameof(MoTa), ref fMoTa, value); }
        }
        string fKhoa;
        public string Khoa
        {
            get { return fKhoa; }
            set { SetPropertyValue<string>(nameof(Khoa), ref fKhoa, value); }
        }
        decimal fHocPhiTheoTichChi;
        [DevExpress.Xpo.DisplayName(@"Học phí theo tín chỉ")]
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "### ### ### ###")]
        public decimal HocPhiTheoTichChi
        {
            get { return fHocPhiTheoTichChi; }
            set { SetPropertyValue<decimal>(nameof(HocPhiTheoTichChi), ref fHocPhiTheoTichChi, value); }
        }
        [Association(@"LichhocReferencesMonhoc"), Aggregated]
        public XPCollection<Lichhoc> Lichhocs { get { return GetCollection<Lichhoc>(nameof(Lichhocs)); } }
        [Association(@"DiemchitietReferencesMonhoc"), Aggregated]
        public XPCollection<Diemchitiet> Diemchitiets { get { return GetCollection<Diemchitiet>(nameof(Diemchitiets)); } }
        [Association(@"DiemdanhReferencesMonhoc"), Aggregated]
        public XPCollection<Diemdanh> Diemdanhs { get { return GetCollection<Diemdanh>(nameof(Diemdanhs)); } }
        [Association(@"HocphichitietReferencesMonhoc"), Aggregated]
        public XPCollection<Hocphichitiet> Hocphichitiets { get { return GetCollection<Hocphichitiet>(nameof(Hocphichitiets)); } }
    }

}
